### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Bhaalspawn** [ruslanfedoseenko/CuteTorrent#18]
Hi,i just discovered this client for torrents. It's nice but i have some question.
Do you have a forum?

About the bug
The first thing i noticed is that the client can't be minimized clicking on the icon on the windows bar. When Cutetorrent is minimized it can be brought in foreground but i can't do the inverse operation.

**Comment by Bhaalspawn** [comment]
are you taking a break from this project?

**Comment by ruslanfedoseenko** [comment]
Just too busy on main work...

**Comment by Bhaalspawn** [comment]
Ok no problem, i like testing new clients so i'm here to report any bug i see and give you suggestions. Cutetorrent seems to be good as i already told you and i'll wait for new versions. maybe yhou could stop developing the search engine and add more features. The search tool already included in the client is good. Extratorrent is one of the best public trackers.
