### ISSUE TITLE
Features needed

### ISSUE THREAD

**Issue by Bhaalspawn** [ruslanfedoseenko/CuteTorrent#19]
The Client is nice,and has a personal interface (even if the style could be better). i like RSS and Search integrated.

I just miss 2 features from the clients i'm using now.
-the first one is really a basic feature and it's very strange that cutetorrent can't do this. it's the renaming of the file inside the torrent. I saw that i can rename the name of the torrent but only the name shown in the client
-the secondo is more rare but it's a very useful feature (utorrent has it). The chance to not create the folder when a torrent is created with a root folder and 1 or more files inside,so you can download those files inside the folder you choose

**Comment by ruslanfedoseenko** [comment]
Functionality of second feature currently can be done by
- selecting one level above
- specifying name same as folder in Add Torrent Dialog.

I you like integrated search - I currently building a torrent indexer and searcher - http://search.cutetorrent.info/index/
later it will be integrated to client.

**Comment by Bhaalspawn** [comment]
yes i know i can do that but it's just not smart because when i select a category i already have the right path. Associating path to categories is very useful because you don't have to select manually the path,that is what i should do if i download a torrent with a folder

Also i see that if i select a category and then chenge the path,i also lose the category selection :(

**Comment by ruslanfedoseenko** [comment]
Added a checkbox in Open Torrent Window "Don't create subfolder with torrent name" to skip creation of a folder with torrent name.
Also added a menu item to rename files

**Comment by Bhaalspawn** [comment]
wow nice but latest version on the website is still 1.0.0.43
