### ISSUE TITLE
Features/help needed [ru]

### ISSUE THREAD

**Issue by wisiwig** [ruslanfedoseenko/CuteTorrent#23]
**Не понравилось / есть вопросы**:
- Почему нельзя установить меньше 50-ти соединений на торрент?  В уТорренте я вообще 3-4 использую.
- Настройки работы с жестким диском для меня неочевидны. 
  а) почему размер кэша выставлен изначально именно 32768 Кб?
  б) что даёт пункт "Разрешить неупорядоченные операции"?
  в) для чего пункт "блокировать файлы"?
  г) что даёт галочка на пункте "использовать кэш чтения"?
  Было бы очень желательно расписать небольшой FAQ по настройкам, имхо. И описание best practices для различных случаев тоже не помешал бы.
- Отсутствие тэгов. Как в том же уТорренте.
- Отчего-то на панели (справа от шестеренки "Настройки") нет ожидаемых (лично мной) кнопок управления выделенным торрентом: запуск скачивания / пауза / остановка... Имхо, это просто напрашивается, нет?
- Поисковые скрипты явно требуют обновления. Если поиск по rutor легко правится заменой в скрипте старого адреса на rutor.is, то с пиратской бухтой или Kickass Torrents всё сложно. При замене адреса бухты на более-менее рабочий piratebay.to понимаешь, что надо переписывать парсер html. Для Kickass есть kickasstorrents.immunicity.cc, но для него тоже надо серьёзно переписывать скрипт.
- Я не нашёл, как можно отключить всплывающее предложение сделать Cute Torrent стандартным приложением для торрентов и магнет-ссылок. 
- В детальной информации по торренту, во вкладке "пиры" хотелось бы кроме возможности добавлять пира (никогда этим не пользовался) иметь возможность забанить пира (или нескольких выбранных пиров). В Cute Torrent ip filter присутствует, кстати? Если нет, очень хотелось бы.
- Ну и portable клиент не помешал бы. А то приходится использовать сборку от portableapps.com

**Comment by ruslanfedoseenko** [comment]
> Отсутствие тэгов. Как в том же уТорренте.

То что ты назвал тегами - это есть группы.
Настраиваются в Настройки -> Фильтрация торрентов.

> Отчего-то на панели (справа от шестеренки "Настройки") нет ожидаемых (лично мной) кнопок управления выделенным торрентом: запуск скачивания / пауза / остановка... Имхо, это просто напрашивается, нет?

![image](https://cloud.githubusercontent.com/assets/4517707/19853307/687d2152-9f79-11e6-916f-d4b52f5e490b.png)
В так скажем блок торрента вынесены эти контролы.

> В детальной информации по торренту, во вкладке "пиры" хотелось бы кроме возможности добавлять пира (никогда этим не пользовался) иметь возможность забанить пира (или нескольких выбранных пиров). В Cute Torrent ip filter присутствует, кстати? Если нет, очень хотелось бы.

IP Фильтры есть но не тестировались. Забаить пира сделаю.
По настройкам жд сдлаю тут на вики FAQ

**Comment by wisiwig** [comment]
Спасибо за оперативный ответ.
Отдельная благодарность за обещание прикрутить бан пиров.

А почему всё-таки нельзя установить меньше 50-ти соединений на торрент? И как отключить всплывающее при запуске предложение сделать Cute Torrent стандартным приложением для торрентов и магнет-ссылок?

Плюс, правда хотелось бы portable клиент...
ЗЫ
Буду ждать FAQ по настройкам жд =)

**Comment by ruslanfedoseenko** [comment]
> А почему всё-таки нельзя установить меньше 50-ти соединений на торрент? И как отключить всплывающее при запуске предложение сделать Cute Torrent стандартным приложением для торрентов и магнет-ссылок?

Мне показалось значение в 50 соединений на торрент оптимальным значением.
Отключить вопрос о стадартном приложении для магниток и торрентов можно только приняв его...

**Comment by wisiwig** [comment]
> Мне показалось значение в 50 соединений на торрент оптимальным значением.
Здесь наши мнения расходятся, как оказалось =)

> Отключить вопрос о стадартном приложении для магниток и торрентов можно только приняв его...
Имхо, странное решение. По-моему стоило бы убрать всплывающее окно и сделать просто пункт в настройках. Но это моё сугубо личное мнение.

> Сделал страничку на вики по настройкам HDD
Спасибо. Большое и человеческое. Всё расписано весьма доступно.
