### ISSUE TITLE
вылет на Win 10

### ISSUE THREAD

**Issue by Gideonis** [ruslanfedoseenko/CuteTorrent#24]
На 10-ке вылетает при сворачивании полноэкранного приложения (игры например) даже если торрент клиент был свернут.
Возможно ошибка в библиотеке пакета C++ на моей машине, но вылет стабильный.
![error](https://cloud.githubusercontent.com/assets/993288/21818702/e01a37da-d779-11e6-8a2b-783962296694.jpg)

**Comment by ruslanfedoseenko** [comment]
Можно. Более подробно описать случай с конкретными примерами? Сам пользуюсь 10 и такого не наблюдал.

**Comment by Gideonis** [comment]
по результатам проверки сегодня виноват оказался все таки компонент системы.
После обновления 10-ки и перезагрузки больше пока не вылетает.
Кстати а предложения обновить до версии 44(которую я не нашел) это баг или некая версия в разработке?

**Comment by Gideonis** [comment]
По всей видимости вылет происходит при попытке развернуть из трея окно клиента после выхода из игры...

**Comment by Gideonis** [comment]
Windows Error Report:
[Report.zip](https://github.com/ruslanfedoseenko/CuteTorrent/files/699338/Report.zip)

**Comment by Gideonis** [comment]
помог откат системы в исходное состояние ( грубо говоря переустановка) теперь вроде все корректно работает.
