### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by psycholyzern** [ruslanfedoseenko/CuteTorrent#6]
Are there any screenshot I can see?

**Comment by ruslanfedoseenko** [comment]
Here is some screenshots
![Main Window](https://cloud.githubusercontent.com/assets/4517707/9459521/1e896304-4b05-11e5-9db8-038e3bae0c69.png)
![Settings Dialog](https://cloud.githubusercontent.com/assets/4517707/9459531/344bb052-4b05-11e5-9bd6-7382788acc80.png)
![Adding torrent](https://cloud.githubusercontent.com/assets/4517707/9459540/5e14c798-4b05-11e5-83bc-54feb11fbda2.png)
![Creating torrent](https://cloud.githubusercontent.com/assets/4517707/9459544/7143d5c0-4b05-11e5-988b-50bd6900e81f.png)
