### ISSUE TITLE
файлы сохраняются в папку System32

### ISSUE THREAD

**Issue by romario08** [ruslanfedoseenko/CuteTorrent#8]
Здравствуйте!
При загрузке файлы сохраняются в папку c:\Windows\System32\
в настройках выбрано сохранять в папку D:\Downloads.

**Comment by ruslanfedoseenko** [comment]
Здравсвуйте можно больше подробностей. 
Файлы из автоматической загрузки или открытые двойным кликом?
Какие конкретно настройки вы выставляли что бы по умолчанию сохранять торренты в D:\Downloads.?
