### ISSUE TITLE
Ошибка загрузки

### ISSUE THREAD

**Issue by rpe001** [ruslanfedoseenko/CuteTorrent#9]
День добрый. Не знаю что случилось в последнее время, но не идет загрузка. Скрин прикрепляю. Однако в других программах (том же uTorrent) все работает стабильно. Не знаю где копать, все настройки перепробовал уже.
![default](https://cloud.githubusercontent.com/assets/16576464/12143511/41baf314-b492-11e5-9afe-b2ceaa720113.jpg)

**Comment by ruslanfedoseenko** [comment]
Не качает потому что нету пиров. А пиров нету потому что у вас кто-то блочит доступ к трекеру(Вероятно провайдер).

**Comment by rpe001** [comment]
Расскажите, как и что посмотреть. Потому что эти же файлы торрента качаются с уТрорента. И при этом не ругается на домен.

**Comment by rpe001** [comment]
Провайдер точно не может, он не менялся. И тем более с uTorrent и других качает сразу, без ошибок подключения и прочего.  понедельник, 11 января 2016г., 13:18 +03:00 от Ruslan < notifications@github.com> :

**Comment by ruslanfedoseenko** [comment]
В строке мнею Выберете Вид и нажмите на пункт Строка состояния.
Должна появится строка состояния внизу
интересует вот эта часть
![image](https://cloud.githubusercontent.com/assets/4517707/12231444/880efd68-b868-11e5-97c0-de67f6d71ea4.png)

**Comment by rpe001** [comment]
DHT 0 подключений. В настройках галочка стоит-не помогает. 
P.S. Пробовал вырубать антивирус, все защиты и т.д. - не помогло. Расскажу маленькую предысторию, вдруг поможет.
За несколько дней до этого пытался создать сеть-раздачу Wi-Fi со своего пк. Но что-то в ходе не получилось, после чего все программы были удалены. И вот через несколько дней заметил, что торрент не работает. Не знаю, может это быть связано или нет. Но... Повторюсь-другие программы-торренты качают успешно, даже не смотря на переименование трекеров и т.д.

**Comment by ruslanfedoseenko** [comment]
Ясно. Вобщем зря я оставил только свою DHT ноду...
Ок вечером вышлю клиент с возможным фиксом.

**Comment by rpe001** [comment]
Ожидаю файл с фиксом. среда, 13 января 2016г., 18:35 +03:00 от Ruslan < notifications@github.com> :

**Comment by rpe001** [comment]
Руслан... Вы пришлете версию другую?

**Comment by ruslanfedoseenko** [comment]
так проблема же с загрузкой решилась и со стартом тоже ? разве нет?

**Comment by rpe001** [comment]
Нет, Вы едь сказали пришлете фикс. Загрузка так и не идет.

**Comment by ruslanfedoseenko** [comment]
Можно получить доступ к машине на которой не идет загрузка через TeamViewer ?

**Comment by rpe001** [comment]
В смысле к ноутбуку? Каким образом? Я в доступе не спец.
--
Отправлено из Mail.Ru для Android суббота, 23 января 2016г., 23:29 +03:00 от Ruslan < notifications@github.com> :

**Comment by ruslanfedoseenko** [comment]
https://get.teamviewer.com/v5v78rw
Пройдите по ссылке запустите программу я увижу когда вы будете онлайн.

**Comment by rpe001** [comment]
Не было возможности запустить. Сегодня включил, оставлю ноут работать.

**Comment by ruslanfedoseenko** [comment]
На выходных если оставить доступ зайду гляну. По среди недели занят был

**Comment by rpe001** [comment]
На выходные оставлял, но присутствия сверхъестественной силы не заметил)

**Comment by ruslanfedoseenko** [comment]
Проблему решили.
